### ISSUE TITLE
为什么我的显示连接不到验证服务器这个是什么问题

### ISSUE THREAD

**Issue by lin752252801** [NiceSprite34/GuanDong_Portal#11]
我已经改了验证地址了
![image](https://user-images.githubusercontent.com/83084897/143010705-289fbdff-70da-484a-85c3-9db3810dacb3.png)
![image](https://user-images.githubusercontent.com/83084897/143010748-47c8cba6-080a-46b4-8f98-33f14a1416d9.png)

**Comment by NiceSprite34** [comment]
用127.0.0.1会拒绝认证，是这样的。你改成自己的LAN IP就可以
