### ISSUE TITLE
大大能不能说一下openrwrt里需要安装哪些ipk

### ISSUE THREAD

**Issue by extreme59** [NiceSprite34/GuanDong_Portal#6]
部署环境

**Comment by NiceSprite34** [comment]
用php7就行

**Comment by NiceSprite34** [comment]
或者电脑用phpstudy，openwrt直接curl他

**Comment by extreme59** [comment]
> 用php7就行

我用老毛子Padavan里内置的ONMP搭建了环境，也把您的登陆器配置进去了，但是不行，不知道那个vhost文件哪里错了，请求帮助。
![112685065-fcb36100-8eae-11eb-9a50-cf2adec73cf0](https://user-images.githubusercontent.com/61527777/122414044-6d9f7c00-cfb9-11eb-93a9-d6acbd8b77ae.png)
![微信图片_20210617221634](https://user-images.githubusercontent.com/61527777/122414410-b5be9e80-cfb9-11eb-8924-07b6647f3c5d.png)

**Comment by extreme59** [comment]
![image](https://user-images.githubusercontent.com/61527777/122415676-b441a600-cfba-11eb-8a25-2ac4d0cc6062.png)

**Comment by NiceSprite34** [comment]
你这个是php没配置好，检查一下php依赖那些

**Comment by extreme59** [comment]
> 你这个是php没配置好，检查一下php依赖那些
就是说nginx配置的没问题，nginx已经pass到php了，就是php方面没弄好是吧。

**Comment by NiceSprite34** [comment]
是的
