### ISSUE TITLE
怎么修改断网时间？我这里断网时间跟index里面的时间不一样

### ISSUE THREAD

**Issue by Wertistyyyy** [NiceSprite34/GuanDong_Portal#7]
↑

**Comment by Wertistyyyy** [comment]
2

**Comment by NiceSprite34** [comment]
index里有断网时间，你改了就行

**Comment by Wertistyyyy** [comment]
我上班上gayhub的时候按错了，不好意思打扰你啦



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: NiceSprite ***@***.***&gt;
发送时间: 2022年2月25日 18:47
收件人: NiceSprite34/GuanDong_Portal ***@***.***&gt;
抄送: Wertistyyyy ***@***.***&gt;, State change ***@***.***&gt;
主题: Re: [NiceSprite34/GuanDong_Portal] 怎么修改断网时间？我这里断网时间跟index里面的时间不一样 (#7)





 
index里有断网时间，你改了就行
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by NiceSprite34** [comment]
没事
